# Generated by Django 3.2.3 on 2021-06-04 11:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_text',
            field=models.TextField(default=121, verbose_name='article text'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='public date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='article',
            field=models.ForeignKey(default=datetime.datetime(2021, 6, 4, 11, 12, 27, 906131, tzinfo=utc), on_delete=django.db.models.deletion.CASCADE, to='articles.article'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='autor_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='comment author'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='comment text'),
            preserve_default=False,
        ),
    ]
